title: backend
description: backend developer path
steps:
  - course: rusdevops/unix
    description: Unix base course
    title: Unix base
  - course: rusdevops/golang
    description: Golang base course
    title: Golang base
  - course: rusdevops/network
    description: Network base course
    title: Network base
  - course: rusdevops/algorithms
    description: Algorithms base course
    title: Algorithms base
  - course: rusdevops/database
    description: Database base course
    title: Database base
  - course: rusdevops/architecture
    description: Architecture base course
    title: Architecture base
  - course: rusdevops/security
    description: Security base course
    title: Security base
  - course: rusdevops/analysis
    description: Analysis base course
    title: Analysis base
  - course: rusdevops/ml
    description: Machine learning base course
    title: ML base
